FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# pip 최신화
RUN python3 -m pip install --upgrade pip

# requirements 먼저 복사해서 설치
COPY requirements.dev.txt .

RUN pip install --no-cache-dir -r requirements.dev.txt

# 소스 복사
COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]