services:
  dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: django_dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    depends_on:
      - db
    restart: unless-stopped

  prod:
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: django_prod
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    depends_on:
      - db
    restart: unless-stopped
    mem_limit: 512m

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
