# Generated by Django 5.2.6 on 2025-09-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_token_is_revoked_tokenblacklist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenblacklist",
            name="user",
        ),
        migrations.DeleteModel(
            name="Token",
        ),
        migrations.DeleteModel(
            name="TokenBlacklist",
        ),
    ]
