# Generated by Django 5.2.6 on 2025-09-25 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("start_period", models.DateTimeField()),
                ("end_period", models.DateTimeField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("긴급", "긴급"),
                            ("높음", "높음"),
                            ("중간", "중간"),
                            ("낮음", "낮음"),
                            ("보류", "보류"),
                        ],
                        default="중간",
                        max_length=10,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("비공개", "비공개"),
                            ("친구공개", "친구공개"),
                            ("전체공개", "전체공개"),
                        ],
                        default="비공개",
                        max_length=10,
                    ),
                ),
                ("is_someday", models.BooleanField(default=False)),
                ("is_recurrence", models.BooleanField(default=False)),
                (
                    "recurrence_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("recurrence_weekdays", models.JSONField(blank=True, null=True)),
                ("recurrence_day_of_month", models.IntegerField(blank=True, null=True)),
                (
                    "recurrence_month_of_year",
                    models.IntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schedule.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "schedule",
            },
        ),
        migrations.CreateModel(
            name="DetailSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_schedule",
                        to="schedule.schedule",
                    ),
                ),
            ],
            options={
                "db_table": "detail_schedule",
            },
        ),
    ]
