# Generated by Django 5.2.6 on 2025-09-22 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("일상", "🏠 일상"),
                            ("취미/여가", "🎨 취미/여가"),
                            ("여행", "✈️ 여행"),
                            ("자기계발/학습", "📚 자기계발/학습"),
                            ("특별이벤트", "🎉 특별이벤트"),
                            ("기타", "🌀 기타"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weekday",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "월"),
                            (1, "화"),
                            (2, "수"),
                            (3, "목"),
                            (4, "금"),
                            (5, "토"),
                            (6, "일"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("긴급", "긴급"),
                            ("높음", "높음"),
                            ("중간", "중간"),
                            ("낮음", "낮음"),
                            ("보류", "보류"),
                        ],
                        default="중간",
                        max_length=10,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[("전체공개", "전체공개"), ("나만보기", "나만보기")],
                        default="나만보기",
                        max_length=20,
                    ),
                ),
                ("is_recurrence", models.BooleanField(default=False)),
                ("start_period", models.DateTimeField()),
                ("end_period", models.DateTimeField()),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("bookmark_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="schedule.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.Case(
                        models.When(priority="긴급", then=0),
                        models.When(priority="높음", then=1),
                        models.When(priority="중간", then=2),
                        models.When(priority="낮음", then=3),
                        models.When(priority="보류", then=4),
                        output_field=models.IntegerField(),
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DetailSchedule",
            fields=[
                ("detail_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("alert_minute", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="schedule.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recurrence",
            fields=[
                ("recurrence_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Daily", "매일"),
                            ("Weekly", "매주"),
                            ("Monthly", "매월"),
                            ("Yearly", "매년"),
                        ],
                        max_length=10,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "month_of_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
                ("until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrences",
                        to="schedule.schedule",
                    ),
                ),
                (
                    "weekdays",
                    models.ManyToManyField(blank=True, related_name="recurrences", to="schedule.weekday"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["user", "created_at"], name="schedule_sc_user_id_91198c_idx"),
        ),
        migrations.AddIndex(
            model_name="detail_schedule",
            index=models.Index(
                fields=["schedule", "start_time", "end_time"],
                name="schedule_de_schedule_972990_idx",
            ),
        ),
    ]
