# Generated by Django 5.2.6 on 2025-09-22 08:12

from django.db import migrations


def forwards_func(apps, schema_editor):
    category = apps.get_model("schedule", "Category")
    db_alias = schema_editor.connection.alias
    categories = ["일상", "취미/여가", "여행", "자기계발/학습", "특별이벤트", "기타"]
    category.objects.using(db_alias).bulk_create(
        [category(name=name) for name in categories],
        ignore_conflicts=True,
    )


def reverse_func(apps, schema_editor):
    category = apps.get_model("schedule", "Category")
    db_alias = schema_editor.connection.alias
    categories = ["일상", "취미/여가", "여행", "자기계발/학습", "특별이벤트", "기타"]
    category.objects.using(db_alias).filter(name__in=categories).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]
    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
