# Generated by Django 5.2.6

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Category = apps.get_model("schedule", "Category")
    db_alias = schema_editor.connection.alias

    categories = [
        {"name": "일상", "code": "daily"},
        {"name": "취미/여가", "code": "hobby"},
        {"name": "여행", "code": "travel"},
        {"name": "자기계발/학습", "code": "learning"},
        {"name": "특별이벤트", "code": "event"},
        {"name": "기타", "code": "other"},
    ]

    Category.objects.using(db_alias).bulk_create(
        [Category(name=c["name"], code=c["code"]) for c in categories],
        ignore_conflicts=True,
    )


def reverse_func(apps, schema_editor):
    Category = apps.get_model("schedule", "Category")
    db_alias = schema_editor.connection.alias

    codes = ["daily", "hobby", "travel", "learning", "event", "other"]
    Category.objects.using(db_alias).filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),  # 이전 마이그레이션 의존
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=20, unique=True, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
