# Generated by Django 5.2.6 on 2025-09-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_populate_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="detailschedule",
            name="detail_id",
        ),
        migrations.RemoveField(
            model_name="recurrence",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="recurrence",
            name="recurrence_id",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="schedule_id",
        ),
        migrations.AddField(
            model_name="category",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AddField(
            model_name="detailschedule",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AddField(
            model_name="recurrence",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
