# Generated by Django 5.2.6 on 2025-09-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_populate_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weekday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "weekday",
            },
        ),
        migrations.RenameField(
            model_name="schedule",
            old_name="is_deleted",
            new_name="complete",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="is_recurrence",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="recurrence_day_of_month",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="recurrence_month_of_year",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="recurrence_type",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="recurrence_weekdays",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_period",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="share_type",
            field=models.CharField(
                choices=[("비공개", "비공개"), ("전체공개", "전체공개")],
                default="비공개",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_period",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("month_of_year", models.PositiveIntegerField(blank=True, null=True)),
                ("day_of_month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_rule",
                        to="schedule.schedule",
                    ),
                ),
                ("weekdays", models.ManyToManyField(blank=True, to="schedule.weekday")),
            ],
            options={
                "db_table": "recurrence_rule",
            },
        ),
    ]
