# Generated by Django 5.2.6

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Weekday = apps.get_model("schedule", "Weekday")
    db_alias = schema_editor.connection.alias

    weekdays = [
        ("월", "월"),
        ("화", "화"),
        ("수", "수"),
        ("목", "목"),
        ("금", "금"),
        ("토", "토"),
        ("일", "일"),
    ]

    Weekday.objects.using(db_alias).bulk_create(
        [Weekday(code=code, name=name) for code, name in weekdays],
        ignore_conflicts=True,
    )


def reverse_func(apps, schema_editor):
    Weekday = apps.get_model("schedule", "Weekday")
    db_alias = schema_editor.connection.alias

    weekdays_codes = ["MO", "TU", "WE", "TH", "FR", "SA", "SU"]
    Weekday.objects.using(db_alias).filter(code__in=weekdays_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_weekday_rename_is_deleted_schedule_complete_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
