# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_populate_weekday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailschedule",
            name="start_time",
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="detailschedule",
            name="end_time",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
